export const site = {
  name: "SharpDev",
  domain: "sharpdev.dev",
  email: "contact@sharpdev.dev",
  tagline: "Design-led web studio",
  /** Generated by `npm run logo` from logo-source.png. */
  logoSrc: "/logo.png",
  description:
    "SharpDev designs and builds fast, beautiful websites — SaaS, e-commerce, 3D and cinematic. You approve the full Figma design before anything goes live.",
  socials: [
    { name: "Instagram", handle: "@sharpdev.dev", href: "https://instagram.com/sharpdev.dev" },
    { name: "Facebook", handle: "@sharpdev.dev", href: "https://facebook.com/sharpdev.dev" },
    { name: "TikTok", handle: "@sharpdev.dev", href: "https://tiktok.com/@sharpdev.dev" },
  ],
} as const;

export const mailto = (subject = "New project enquiry") =>
  `mailto:${site.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(
    `Hi SharpDev,

My business:
What I need:
Rough deadline:
Website I like:

Thanks,`,
  )}`;

export const nav = [
  { label: "Work", href: "#work" },
  { label: "Services", href: "#services" },
  { label: "Process", href: "#process" },
  { label: "Stack", href: "#stack" },
  { label: "FAQ", href: "#faq" },
] as const;
