import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { site } from "@/lib/site";
import { DEFAULT_LANG, isLang, LANG_COOKIE } from "@/lib/lang";
import { LangProvider } from "@/components/LangProvider";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const instrument = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: "400",
  style: ["italic", "normal"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(`https://${site.domain}`),
  title: {
    default: "SharpDev — Web design & development studio",
    template: "%s — SharpDev",
  },
  description: site.description,
  keywords: [
    "web design studio",
    "Next.js development",
    "Figma web design",
    "SaaS website",
    "e-commerce website",
    "3D website",
    "WebGL",
    "cinematic website",
  ],
  openGraph: {
    title: "SharpDev — Web design & development studio",
    description: site.description,
    url: `https://${site.domain}`,
    siteName: "SharpDev",
    type: "website",
    locale: "en",
    images: [{ url: "/logo-og.png", width: 1200, height: 630, alt: "SharpDev" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "SharpDev — Web design & development studio",
    description: site.description,
    images: ["/logo-og.png"],
  },
  // Favicons come from the src/app/icon*.png file convention (512/32/16)
  // plus apple-icon.png, all generated by `npm run logo`.
  alternates: { canonical: "/" },
};

export const viewport: Viewport = {
  themeColor: "#06070a",
  colorScheme: "dark",
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "SharpDev",
  description: site.description,
  email: site.email,
  url: `https://${site.domain}`,
  serviceType: [
    "Web design",
    "Web development",
    "SaaS websites",
    "E-commerce websites",
    "3D & WebGL websites",
  ],
  sameAs: site.socials.map((s) => s.href),
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Resolved on the server so `lang` and the copy are right on first paint.
  const stored = (await cookies()).get(LANG_COOKIE)?.value;
  const lang = isLang(stored) ? stored : DEFAULT_LANG;

  return (
    <html lang={lang} className={`${geist.variable} ${geistMono.variable} ${instrument.variable}`}>
      <body className="grain antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <LangProvider lang={lang}>{children}</LangProvider>
      </body>
    </html>
  );
}
